version: '3.8'

services:
  challenge05-app:
    image: wyataco/challenge05-app:1.0
    container_name: service-flask-app
    ports:
      - 8000:8000
    networks:
      - challenge05

  challenge05-consumer:
    image: wyataco/challenge05-consumer:1.0
    container_name: service-consumer
    environment:  
      - LOCAL=true  
      - PYTHONUNBUFFERED=1
    networks:
      - challenge05

networks:
  challenge05: