apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  labels:
    app: nginx-server 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-server

